version: 2.1

references:
  primary_containers: &primary_containers
    docker:
      - image: circleci/buildpack-deps:18.04

  build_run: &build_run
    run:
      name: build
      environment:
        CONTAINER_NAME: qkm_firmware
      command: |
        set -x
        git submodule init
        git submodule update
        docker image build -t $CONTAINER_NAME .
        docker container run --name $CONTAINER_NAME $CONTAINER_NAME make helix:luciferous_helix
        docker container run --name $CONTAINER_NAME $CONTAINER_NAME make shiro:luciferous
        docker container cp $CONTAINER_NAME:/qmk_firmware/.build .
        docker container rm $CONTAINER_NAME
        cd .build
        ls -F | grep / | xargs rm -rf

jobs:
  build_helix_luciferous_helix:
    <<: *primary_containers
    steps:
      - checkout
      - setup_remote_docker
      - <<: *build_run
        environment:
          BUILD_TARGET: helix:luciferous_helix
      - store_artifacts:
        path: .build

workflows:
  version: 2
  build:
    jobs:
      - build_helix_luciferous_helix
