version: 2.1

references:
  primary_containers: &primary_containers
    docker:
      - image: circleci/buildpack-deps:18.04

jobs:
  build_helix_luciferous_helix:
    <<: *primary_containers
    environment:
      BUILD_TARGET: helix:luciferous_helix
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          environment:
            CONTAINER_NAME: qkm_firmware
          command: |
            set -x
            docker image build -t $CONTAINER_NAME .
            docker container run --name qmk_firmware $CONTAINER_NAME make $BUILD_TARGET
            docker container cp $CONTAINER_NAME:/qmk_firmware/.build .
            docker container rm $CONTAINER_NAME
      - store_artifacts:
          path: .build

  build_helix_luciferous_helix_02:
    <<: *primary_containers
    environment:
      BUILD_TARGET: helix:luciferous_helix
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          environment:
            CONTAINER_NAME: qkm_firmware
          command: |
            set -x
            docker image build -t $CONTAINER_NAME .
            docker container run --name qmk_firmware $CONTAINER_NAME make $BUILD_TARGET
            docker container cp $CONTAINER_NAME:/qmk_firmware/.build .
            docker container rm $CONTAINER_NAME
      - store_artifacts:
          path: .build

  build_helix_luciferous_helix_03:
    <<: *primary_containers
    environment:
      BUILD_TARGET: helix:luciferous_helix
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          environment:
            CONTAINER_NAME: qkm_firmware
          command: |
            set -x
            docker image build -t $CONTAINER_NAME .
            docker container run --name qmk_firmware $CONTAINER_NAME make $BUILD_TARGET
            docker container cp $CONTAINER_NAME:/qmk_firmware/.build .
            docker container rm $CONTAINER_NAME
      - store_artifacts:
          path: .build

workflows:
  version: 2
  build:
    jobs:
      - build_helix_luciferous_helix
      - build_helix_luciferous_helix_02
      - build_helix_luciferous_helix_03
