name: Generate Docs

on:
  push:
    branches:
    - master
    paths:
    - 'tmk_core/**'
    - 'quantum/**'
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:
  generate:
    runs-on: ubuntu-latest

    # protect against those who develop with their fork on master
    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: sudo apt install nodejs doxygen
    - name: Build docs
      run: |
        bin/qmk docs --build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: .build/docs
