name: Generate Docs

on:
  push:
    branches:
    - master
    - develop
    paths:
    - 'tmk_core/**'
    - 'quantum/**'
    - 'platforms/**'
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    # protect against those who develop with their fork on master
    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y rsync nodejs npm
        npm install -g lunr lunr-languages
        python3 -m pip install mkdocs-git-revision-date-plugin mkdocs-material mkdocs-literate-nav mkdocs-same-dir pygments

    - name: Build docs
      run: ./util/build_translations.sh ${{ github.ref }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: site
        git-config-email: hello@qmk.fm
        target-folder: ${{ github.ref }}
