name: PR keyboards

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'util/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Print info
        run: |
          git rev-parse --short HEAD
          git diff remotes/origin/${{ github.base_ref }} --name-only

      - name: Run
        run: |
          qmk info -kb zvecr/split_blackpill 2>&1 | tee /tmp/$$
          grep ☒ /tmp/$$
