name: PR keyboards/keymaps

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'util/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: '\n'

    - name: Print git info
      run: |
        git rev-parse --short HEAD
        echo ${{ github.event.pull_request.base.sha }}
        echo '${{ steps.file_changes.outputs.files}}'

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u '+%s')"
      shell: bash

    - uses: actions/cache@v2
      with:
        path: |
          .ccache/
        key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ steps.get-date.outputs.date }}
        # Restoring: From current branch, otherwise from base branch.
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.ref }}
          ${{ runner.os }}-ccache-${{ github.base_ref }}

    - name: Build 
      shell: 'bash {0}'
      env:
        MAKEFLAGS: '-j3 --output-sync'
      run: |
        apt-get update && apt-get install --no-install-recommends -y ccache
        export PATH="/usr/lib/ccache:$PATH"
        export CCACHE_DIR=.ccache
        make all:default
        ccache -s
