name: PR Lint keyboards

on:
  pull_request:
    paths:
    - 'keyboards/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes
      with:
        output: '\n'
        fileOutput: '\n'

    - name: Print git info
      run: |
        git rev-parse --short HEAD
        echo ${{ github.event.pull_request.base.sha }}
        echo '${{ steps.file_changes.outputs.files}}'

    - name: Run qmk info
      shell: 'bash {0}'
      run: |
        qmk select --filter=kb $(cat $HOME/files.txt) | xargs -l1 qmk info -l -kb

    - name: Run qmk lint
      shell: 'bash {0}'
      run: |
        qmk select --filter=kb $(cat $HOME/files.txt) | xargs -l1 qmk lint -kb
