name: Automated Tests

on:
  push:
    paths:
    - .github/**/*
    - quantum/**/*
    - tmk_core/**/*
    - drivers/**/*
    - tests/**/*
    - util/**/*
    - platforms/**/*
    - Makefile
    - '*.mk'

jobs:
  test:
    name: 'make test:all'
    runs-on: ubuntu-latest
    container: qmkfm/base_container

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Test
      run: |
        make -j3 -O test:all
