name: pcilabs firmware CI

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: "Branch to build"
        options: [master, develop]
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    
    steps:
    - name: setup qmk
      uses: actions/checkout@master
    - name: compile firmware for all keyboards
      continue-on-error: true
      run: qmk mass-compile -j0 -f "manufacturer=PCI Labs" || touch .failed
    - name: upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{github.base_ref || github.ref_name}}
        if-no-files-found: ignore
        path: |
            *.bin
            *.hex
            *.uf2
            .build/failed.*
            .failed
      
