name: PR keyboards/keymaps

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'util/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container: qmkfm/base_container

    steps:
      env:
        MAKEFLAGS: '-j --output-sync'
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Print info
      run: |
        git rev-parse --short HEAD
        git diff remotes/origin/${{ github.base_ref }} --name-only
    - name: Run build
      run: make all:default
